# Site settings
title: Gaussian Process Winter School, Genova, Italy, 2015
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2015 Gaussian Process Winter School hosted by the University of Genoa.
baseurl: "/gprs15a/" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Alessandro Rudi, url: "http://www.iit.it/it/who-we-are/icub-facility-people/alessandro-rudi.html"}
  - {name: Lorenzo Rosasco, url: "http://web.mit.edu/lrosasco/www/"}
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Alessandro Rudi, url: "http://www.iit.it/it/who-we-are/icub-facility-people/alessandro-rudi.html"}
  - {name: Lorenzo Rosasco, url: "http://web.mit.edu/lrosasco/www/"}
  name: Gaussian Process Winter School
  hosturl: http://lcsl.mit.edu/courses/gpws/
  location: Università di Genoa, Italy
  year: 2015
  month: January
  dates:
  - {date: 19, day: Monday, month: January, year: 2015}
  - {date: 20, day: Tuesday, month: January, year: 2015}
  - {date: 21, day: Wednesday, month: January, year: 2015}
  - {date: 22, day: Thursday, month: January, year: 2015}
  
# Build settings
markdown: kramdown

